import { useState } from "react";
import { Modal, Pressable, ScrollView, View } from "react-native";
import { Check, ChevronDown } from "lucide-react-native";
import { useLanguage } from "../../application/LanguageContext";
import { AppButton, ThemedText as Text } from "../../core/components";
import { useTheme } from "../theme/ThemeProvider";
export function SelectField({ label, value, options, onChange, disabled, error, helper }: { label: string; value: string; options: { value: string; label: string; disabled?: boolean }[]; onChange: (value: string) => void; disabled?: boolean; error?: string | null; helper?: string }) {
  const { colors } = useTheme(); const { t } = useLanguage(); const [open, setOpen] = useState(false); const selected = options.find(option => option.value === value);
  return <View style={{ gap: 6 }}><Text style={{ fontSize: 13, fontWeight: "600", color: colors.ink2 }}>{t(label)}</Text><Pressable accessibilityRole="button" accessibilityLabel={t("Choose {0}", t(label))} accessibilityState={{ disabled: Boolean(disabled), expanded: open }} disabled={disabled} onPress={() => setOpen(true)} style={{ minHeight: 52, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 14, backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: error ? colors.criticalText : colors.line, opacity: disabled ? .5 : 1 }}><Text style={{ flex: 1 }}>{selected?.label ?? t("Choose…")}</Text><ChevronDown size={18} color={colors.ink3} /></Pressable>{error ? <Text accessibilityRole="alert" style={{ color: colors.criticalText, fontSize: 13 }}>{t(error)}</Text> : helper ? <Text style={{ color: colors.ink3, fontSize: 13 }}>{t(helper)}</Text> : null}
    <Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={{ flex: 1, backgroundColor: colors.scrim, justifyContent: "flex-end" }}><Pressable accessibilityLabel={t("Cancel")} onPress={() => setOpen(false)} style={{ flex: 1 }} /><View accessibilityViewIsModal style={{ maxHeight: "75%", margin: 8, padding: 20, paddingBottom: 32, borderRadius: 38, gap: 12, backgroundColor: colors.surface }}><View style={{ alignSelf: "center", width: 36, height: 5, borderRadius: 3, backgroundColor: colors.line }} /><Text accessibilityRole="header" style={{ fontSize: 22, fontWeight: "700" }}>{t(label)}</Text><ScrollView>{options.map(option => <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{ selected: option.value === value, disabled: Boolean(option.disabled) }} disabled={option.disabled} onPress={() => { onChange(option.value); setOpen(false); }} style={{ minHeight: 52, paddingHorizontal: 12, flexDirection: "row", gap: 12, alignItems: "center", borderRadius: 12, backgroundColor: option.value === value ? colors.sunTint : "transparent", opacity: option.disabled ? .5 : 1 }}><Text style={{ flex: 1 }}>{option.label}</Text>{option.value === value ? <Check size={20} color={colors.ink} /> : null}</Pressable>)}</ScrollView><AppButton label="Cancel" variant="ghost" onPress={() => setOpen(false)} /></View></View></Modal>
  </View>;
}
