apiVersion: apps/v1
kind: Deployment
metadata:
  name: deye-solar
  namespace: deye-solar
  labels:
    app: deye-solar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deye-solar
  template:
    metadata:
      labels:
        app: deye-solar
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: deye-solar
          image: ghcr.io/dmitryshapar3/deye-solar:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver-service.production.svc.cluster.local,1433;Database=DeyeSolar;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
            - name: Tuya__BaseUrl
              value: "https://openapi.tuyaeu.com"
            - name: Tuya__AccessId
              value: "fyr4m9uxqadjuw4rvmdc"
            - name: Tuya__AccessSecret
              value: "c3099c3843f846bba8419ef873881191"
            - name: Tuya__DeviceId
              value: "bf116cf4ab715a97583cmi"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
