apiVersion: apps/v1
kind: Deployment
metadata:
  name: deye-solar
  namespace: deye-solar
  labels:
    app: deye-solar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deye-solar
  template:
    metadata:
      labels:
        app: deye-solar
    spec:
      containers:
        - name: deye-solar
          image: ghcr.io/dmitryshapar3/deye-solar:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver-service.production.svc.cluster.local,1433;Database=DeyeSolar;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
