apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deye-solar-integration-packages
  namespace: deye-solar
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deye-solar-protection-keys
  namespace: deye-solar
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deye-solar-integration-bundle
  namespace: deye-solar
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
