apiVersion: v1
kind: Service
metadata:
  name: deye-solar
  namespace: deye-solar
spec:
  type: NodePort
  selector:
    app: deye-solar
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880
