apiVersion: v1
kind: Secret
metadata:
  name: deye-solar-shelly
  namespace: deye-solar
type: Opaque
stringData:
  backend-mode: CloudShelly
  server-uri: https://shelly-000-eu.shelly.cloud
  auth-key: replace-with-shelly-authorization-cloud-key
  device-id: replace-after-selecting-device-or-leave-empty
