import type { NavigatorScreenParams } from "@react-navigation/native";
import type { ExportSalesPeriod, SolarHistoryPeriod } from "../core/api/types";
export type HomeStackParamList = { Home: undefined; LiveReadings: undefined; Settings: undefined; ReadingsLog: undefined;
  SolarSite: undefined; TariffExport: undefined; ConnectedServices: undefined; DataRefresh: undefined;
  Language: undefined; TimeZone: undefined; Appearance: undefined; SignInSecurity: undefined; PasswordSessions: undefined;
  ChangePassword: undefined; DeleteAccount: undefined; EditProfile: undefined; Server: undefined; };
export type AutomationsStackParamList = { AutomationsList: undefined; Activity: undefined; ReadingsLog: undefined };
export type RootTabsParamList = { HomeTab: NavigatorScreenParams<HomeStackParamList> | undefined; Energy: { segment?: "Production" | "Export" } | undefined; Devices: undefined; Automations: NavigatorScreenParams<AutomationsStackParamList> | undefined;
 };
export type RootStackParamList = { MainTabs: NavigatorScreenParams<RootTabsParamList> | undefined;
  AccountSettings: NavigatorScreenParams<HomeStackParamList> | undefined;
  AutomationEditor: { id?: number; template?: "solar" | "reserve" | "daylight" } | undefined; DeviceSheet: { id: string }; ManualOverride: { id: string; isOn: boolean };
  Connect: { kind?: "inverter" | "socket"; instanceId?: string } | undefined; Paywall: undefined;
  ProductionHourlySheet: { period?: SolarHistoryPeriod; date?: string; from?: string; through?: string; selectedTimestamp?: string } | undefined;
  ExportHourlySheet: { period?: ExportSalesPeriod; date?: string; from?: string; through?: string; includeUpcoming?: boolean } | undefined;
  DesignGallery: undefined; };
export type AuthStackParamList = { Welcome: undefined; CodeRequest: { channel?: "email" | "phone" } | undefined; EmailCode: { channel: "email" | "phone"; destination: string; verificationId: string; expiresAt: string; retryAfterSeconds: number }; PasswordLogin: undefined; Server: undefined; };
