import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, View } from "react-native";
import { useNavigation, usePreventRemove, useRoute, type NavigationProp, type RouteProp } from "@react-navigation/native";
import { Check, Plug, Sun } from "lucide-react-native";
import { useAuth } from "../../application/AuthContext";
import { useLanguage } from "../../application/LanguageContext";
import { useScopedAction } from "../../application/useScopedAction";
import type { RootStackParamList } from "../../application/navigationTypes";
import type { IntegrationCatalog, IntegrationDiscovery, IntegrationDeviceBinding, IntegrationProvider, SecretOperation } from "../../core/api/IntegrationApi";
import { AppButton, Card, DataRow, EmptyState, ErrorBanner, Header, LoadingState, Screen, SectionTitle, SegmentedControl, StatusPill, TextField, ThemedText as Text } from "../../core/components";
import { useTheme } from "../../ui/theme/ThemeProvider";
import { IntegrationFields } from "../integrations/IntegrationFields";
import { applyIntegrationOAuth, createIntegrationDraft, integrationChange, integrationDraftChanged, unsupportedProvider, type IntegrationDraft } from "../integrations/integrationDraft";
import { authorizeIntegration } from "../integrations/integrationOAuth";
import type { BillingAccess } from "../subscription/billingPolicy";
import { canSelectSocket, discoveryFacts, matchingBinding, trialSocketRemaining } from "./connectPolicy";

type CatalogKinds = IntegrationCatalog & { providerKinds?: Record<string, string[]> };
export function ConnectScreen() {
  const navigation = useNavigation<NavigationProp<RootStackParamList>>(); const route = useRoute<RouteProp<RootStackParamList, "Connect">>(); const { api, apiBaseUrl } = useAuth(); const { t } = useLanguage(); const { colors } = useTheme();
  const [catalog, setCatalog] = useState<CatalogKinds | null>(null); const [kind, setKind] = useState<"inverter" | "socket">(route.params?.kind ?? "inverter"); const [step, setStep] = useState(0); const [draft, setDraft] = useState<IntegrationDraft | null>(null); const [loading, setLoading] = useState(true); const [canEdit, setCanEdit] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [discovery, setDiscovery] = useState<IntegrationDiscovery | null>(null); const [names, setNames] = useState<Record<string, string>>({}); const [selected, setSelected] = useState<string[]>([]); const [now, setNow] = useState(Date.now()); const [bindings, setBindings] = useState<IntegrationDeviceBinding[]>([]); const [quotaAccess, setQuotaAccess] = useState<BillingAccess | null>(null);
  const actions = useScopedAction(api, `${apiBaseUrl}:${route.params?.instanceId ?? "new"}`, () => { setCatalog(null); setDraft(null); setLoading(true); setError(null); setDiscovery(null); setSelected([]); setCanEdit(false); setBindings([]); setQuotaAccess(null); setNames({}); setNotice(null); setStep(0); }); const busy = Boolean(actions.busy); const unsupported = draft ? unsupportedProvider(draft.provider) : null;
  usePreventRemove(Boolean(draft && integrationDraftChanged(draft)), ({ data }) => Alert.alert(t("Discard changes?"), t("The saved connection is kept. Unsaved credentials will be discarded."), [{ text: t("Keep editing"), style: "cancel" }, { text: t("Discard"), style: "destructive", onPress: () => navigation.dispatch(data.action) }]));
  const run = (label: string, action: Parameters<typeof actions.run>[1]) => actions.run(label, action, { started: () => { setError(null); setNotice(null); }, failed: e => setError(e instanceof Error ? e.message : "Connection could not be completed.") });
  const load = useCallback(() => actions.run("load", async context => {
    const [next, permissions] = await Promise.all([api.integrations.getCatalog(context.signal), api.accountSecurity.getPermissions(context.signal)]);
    let nextDraft: IntegrationDraft | null = null; let nextBindings: IntegrationDeviceBinding[] = [];
    if (route.params?.instanceId) { const config = await api.integrations.getConfiguration(route.params.instanceId, context.signal); const [provider, existing] = await Promise.all([api.integrations.getProvider(config.instance.providerId, config.instance.packageVersion, context.signal), api.integrations.getDevices(config.instance.id, context.signal)]); nextDraft = createIntegrationDraft(provider, config); nextBindings = existing; }
    context.publish(() => { setCatalog(next); setCanEdit(permissions.permissions.includes("ManageIntegrations")); setDraft(nextDraft); setStep(nextDraft ? 1 : 0); setDiscovery(null); setSelected([]); setBindings(nextBindings); setQuotaAccess(null); setNames({}); setLoading(false); });
  }, { failed: e => { setError(e instanceof Error ? e.message : "Providers could not be loaded."); setLoading(false); } }), [api, actions.run, route.params?.instanceId]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const providers = useMemo(() => catalog?.providers.filter(provider => { const kinds = catalog.providerKinds?.[provider.providerId]; return !kinds || kinds.includes(kind); }) ?? [], [catalog, kind]);
  function choose(provider: IntegrationProvider) { return run("create", async context => { const instance = await api.integrations.create(provider.providerId, provider.displayName, context.signal); const config = await api.integrations.getConfiguration(instance.id, context.signal); const pinned = await api.integrations.getProvider(instance.providerId, instance.packageVersion, context.signal); context.publish(() => { setDraft(createIntegrationDraft(pinned, config)); setBindings([]); setQuotaAccess(null); setNames({}); setStep(1); }); }); }
  function changeValue(key: string, value: string) { setDraft(current => current && { ...current, values: { ...current.values, [key]: value } }); setDiscovery(null); }
  function changeSecret(key: string, value: SecretOperation) { setDraft(current => current && { ...current, secrets: { ...current.secrets, [key]: value } }); setDiscovery(null); }
  function action(name: string) {
    if (!draft) return null;
    if (name === "oauth") return <AppButton key={name} label={t("Continue to {0}", draft.provider.displayName)} disabled={busy || !canEdit || Boolean(unsupported)} variant="secondary" onPress={() => void run("oauth", async context => { const ready = await authorizeIntegration(api.integrations, draft.configuration.instance.id, integrationChange(draft, { allowMissingOAuthSecrets: true }), context.signal); if (ready) context.publish(() => { setDraft(current => current && applyIntegrationOAuth(current, ready)); setNotice("Authorization ready. Save this connection to keep it."); setDiscovery(null); }); })} />;
    if (name === "test") return <AppButton key={name} label="Check connection" variant="secondary" disabled={busy || !canEdit || Boolean(unsupported)} loading={actions.busy === "test"} onPress={() => void run("test", async context => { const result = await api.integrations.test(draft.configuration.instance.id, integrationChange(draft), context.signal); context.publish(() => { if (!result.success) setError(result.message); else setNotice("Connection works. Nothing was switched."); }); })} />;
    if (name === "discover") return <AppButton key={name} label="Find devices" variant="secondary" disabled={busy || !canEdit || Boolean(unsupported)} loading={actions.busy === "discover"} onPress={() => void findDevices()} />;
    return null;
  }
  function findDevices() { if (!draft) return; return run("discover", async context => {
    const [found, access] = await Promise.allSettled([api.integrations.discover(draft.configuration.instance.id, integrationChange(draft), context.signal), api.getBillingAccess(context.signal)]);
    if (found.status === "rejected") throw found.reason;
    const result = found.value;
    context.publish(() => { setDiscovery(result); setQuotaAccess(access.status === "fulfilled" ? access.value : null); setNames(Object.fromEntries(result.devices.map(device => [device.selectionToken, matchingBinding(device, bindings)?.displayName ?? device.name]))); setSelected([]); setStep(2); setNotice(t("{0} devices found. Nothing was switched.", result.devices.filter(device => device.kind === kind).length)); });
  }); }
  function save() { if (!draft) return; return run("save", async context => { const saved = await api.integrations.saveConfiguration(draft.configuration.instance.id, integrationChange(draft), context.signal); context.publish(() => { setDraft(createIntegrationDraft(draft.provider, saved)); setDiscovery(null); setNotice("Connection saved"); }); }); }
  function select(token: string) {
    if (!draft || !discovery || !canEdit || Date.parse(discovery.expiresAt) <= Date.now()) return;
    const source = discovery.devices.find(item => item.selectionToken === token);
    if (!source || matchingBinding(source, bindings) || selected.includes(token)
      || source.kind === "socket" && !canSelectSocket(quotaAccess)) return;
    return run("select", async context => {
      const candidate = names[token]?.trim() ?? source.name;
      const displayName = source.kind === "socket" && candidate !== source.name ? candidate : undefined;
      const binding = await api.integrations.selectDevice(draft.configuration.instance.id, integrationChange(draft), token, context.signal, displayName);
      context.publish(() => { setSelected(items => [...items, token]); setBindings(items => [...items.filter(item => item.id !== binding.id), binding]); setQuotaAccess(null); setNotice(binding.displayName ? "Device connected and named" : "Device connected"); });
      const [config, access] = await Promise.allSettled([api.integrations.getConfiguration(draft.configuration.instance.id, context.signal), api.getBillingAccess(context.signal)]);
      context.publish(() => { if (config.status === "fulfilled") setDraft(createIntegrationDraft(draft.provider, config.value)); setQuotaAccess(access.status === "fulfilled" ? access.value : null); });
    });
  }
  function enable() { if (!draft) return; return run("enable", async context => { const instance = draft.configuration.instance; const enabled = await api.integrations.setEnabled(instance.id, true, { expectedRevision: instance.revision, packageVersion: instance.packageVersion, packageDigest: instance.packageDigest, descriptorDigest: instance.descriptorDigest }, context.signal); context.publish(() => { setDraft(current => current && { ...current, configuration: { ...current.configuration, instance: enabled } }); setNotice("Connection enabled"); }); }); }
  const devices = discovery?.devices.filter(device => device.kind === kind) ?? []; const expired = Boolean(discovery && now >= Date.parse(discovery.expiresAt));
  return <Screen refreshing={loading || busy} onRefresh={async () => { if (draft && integrationDraftChanged(draft)) { Alert.alert(t("Discard changes?"), t("Reloading replaces your unsaved changes."), [{ text: t("Keep editing"), style: "cancel" }, { text: t("Discard"), style: "destructive", onPress: () => void load() }]); } else await load(); }}><Header title={step === 0 ? "Connect a service" : step === 1 ? "Connect your account" : "Choose devices"} subtitle={t("Step {0} of 3", step + 1)} /><ErrorBanner message={error ?? unsupported} />{notice ? <StatusPill label={notice} tone="success" /> : null}{loading ? <LoadingState /> : null}
    {!canEdit && !loading ? <EmptyState title="Owner access required" detail="Ask the installation owner to connect services." /> : null}
    {step === 0 && !loading ? <><SegmentedControl options={[{ label: "Inverter", value: "inverter" }, { label: "Smart plug", value: "socket" }]} value={kind} onChange={value => { if (!busy) setKind(value); }} /><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 12 }}>{providers.map(provider => <View key={`${provider.providerId}:${provider.packageVersion}`} style={{ width: "47%" }}><Card style={{ gap: 14 }}><Text style={{ fontSize: 32, fontWeight: "700", color: colors.solar }}>{provider.displayName.slice(0, 1).toUpperCase()}</Text><Text>{provider.displayName}</Text><AppButton label="Connect" variant="quiet" disabled={busy || !canEdit || Boolean(unsupportedProvider(provider))} onPress={() => void choose(provider)} /></Card></View>)}</View>{!providers.length ? <EmptyState title="No supported providers" detail="The server has no installed provider for this device type." /> : null}</> : null}
    {step === 1 && draft ? <><Card style={{ gap: 14 }}><SectionTitle title={draft.provider.displayName} /><TextField label="Connection name" value={draft.configuration.instance.name} onChangeText={value => setDraft(current => current && { ...current, configuration: { ...current.configuration, instance: { ...current.configuration.instance, name: value } } })} editable={false} /><IntegrationFields draft={draft} disabled={busy || !canEdit || Boolean(unsupported)} onValue={changeValue} onSecret={changeSecret} renderAction={action} />{draft.provider.providerId.includes("shelly") ? <Text style={{ color: colors.ink3, fontSize: 13 }}>{t("In Shelly Cloud, open User settings → Authorization cloud key.")}</Text> : null}</Card><AppButton label="Save connection" loading={actions.busy === "save"} disabled={busy || !canEdit || Boolean(unsupported)} onPress={() => void save()} /><AppButton label="Choose devices" icon={kind === "inverter" ? Sun : Plug} variant="secondary" disabled={busy || !canEdit || Boolean(unsupported)} onPress={() => void findDevices()} /></> : null}
    {step === 2 ? <>{quotaAccess?.status === "trial" && kind === "socket" ? <Card style={{ backgroundColor: colors.sunTint }}><Text>{t("Your free month includes 1 smart plug. Additional plugs require Premium.")}</Text>{trialSocketRemaining(quotaAccess) !== null ? <DataRow label="Smart plugs" value={t("{0} of 1", quotaAccess.socketUsage)} /> : null}</Card> : null}{kind === "socket" && !quotaAccess && !busy ? <ErrorBanner message="Your account access could not be checked. Connect to the server and try again." /> : null}{expired ? <ErrorBanner message="Device choices expired. Pull down or return to credentials and find devices again." /> : null}{devices.length ? devices.map(device => {
      const facts = discoveryFacts(device); const existing = matchingBinding(device, bindings); const connected = selected.includes(device.selectionToken) || Boolean(existing); const premium = device.kind === "socket" && !connected && trialSocketRemaining(quotaAccess) === 0;
      return <Card key={device.selectionToken} style={{ gap: 12 }}><SectionTitle title={existing?.displayName ?? device.name} trailing={connected ? <StatusPill label="Connected" tone="success" /> : premium ? <StatusPill label="Premium" tone="warning" /> : facts.online === false ? <StatusPill label="Offline" tone="warning" /> : facts.online === true ? <StatusPill label="Online" tone="success" /> : <StatusPill label="Status unknown" />} /><DataRow label="Device ID" value={device.remoteId} />{device.kind === "socket" ? <TextField label="Name in SmartSolar" value={names[device.selectionToken] ?? device.name} onChangeText={value => setNames(current => ({ ...current, [device.selectionToken]: value }))} maxLength={80} editable={!busy && !connected && canEdit} /> : null}{facts.canSwitch === false ? <Text style={{ color: colors.ink3 }}>{t("This device reports readings but cannot be switched.")}</Text> : null}<AppButton label={connected ? "Connected" : "Add device"} icon={connected ? Check : undefined} disabled={busy || expired || connected || premium || device.kind === "socket" && !canSelectSocket(quotaAccess) || !canEdit} onPress={() => void select(device.selectionToken)} /></Card>;
    }) : <EmptyState title="No devices found" />}<AppButton label="Back to credentials" variant="secondary" disabled={busy} onPress={() => setStep(1)} />{draft?.configuration.instance.status !== "enabled" ? <AppButton label="Enable connection" disabled={busy || !canEdit || !selected.length} loading={actions.busy === "enable"} onPress={() => void enable()} /> : null}<AppButton label="Done" variant="quiet" disabled={busy} onPress={() => navigation.goBack()} /></> : null}
  </Screen>;
}
