using System.Security.Claims;
using DeyeSolar.Web.Auth;
using DeyeSolar.Web.Localization;
using DeyeSolar.Web.Billing;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.RateLimiting;
namespace DeyeSolar.Web.Pages;
[Authorize,EnableRateLimiting("identity-auth")]
public sealed class AccountSettingsModel(AccountManagementService management,AccountIdentityService identities,
 AccountSecurityService security,AccountFreshProofVerifier fresh,
 AuthProviderOptions providers,ExternalAccountProofService external,AppleIdentityFlowStore apple,
 GoogleMobileTicketStore googleTickets,UserLanguageService languages,
 IBillingAccessReader billing):PageModel
{
 [BindProperty]public string? DisplayName{get;set;}[BindProperty]public string? DisplayTimeZoneId{get;set;}[BindProperty]public string Language{get;set;}="en";
 [BindProperty]public string Operation{get;set;}="";[BindProperty]public string CurrentPassword{get;set;}="";[BindProperty]public string NewPassword{get;set;}="";[BindProperty]public string VerificationId{get;set;}="";[BindProperty]public string Code{get;set;}="";[BindProperty]public string Channel{get;set;}="email";[BindProperty]public string Destination{get;set;}="";[BindProperty]public string ChallengeId{get;set;}="";[BindProperty]public string ContactCode{get;set;}="";[BindProperty]public Guid SessionId{get;set;}[BindProperty]public string Provider{get;set;}="google";[BindProperty]public bool ConfirmDelete{get;set;}
 [TempData]public string? ExternalFlowId{get;set;}[TempData]public string? ExternalProofId{get;set;}[TempData]public string? PendingOperation{get;set;}[TempData]public string? PendingSessionId{get;set;}
 public AccountProfile Profile{get;private set;}=new(null,null,null);public AccountPreferences Preferences{get;private set;}=new(null);public AccountIdentitiesResponse? Identities{get;private set;}public AccountSessionsResponse Sessions{get;private set;}=new([]);public DeyeSolar.Domain.Billing.BillingAccess? Access{get;private set;}public AuthProviderOptions Providers=>providers;public string? ErrorMessage{get;private set;}public string? Notice{get;private set;}public string? ContactDestination{get;private set;}public DateTimeOffset? ContactExpiresAt{get;private set;}public int RetryAfterSeconds{get;private set;}public bool Prepared=>Operations.Contains(Operation);public bool HasExternalProof=>ExternalProofId is not null;
 public static readonly string[] Operations=["unlink-google","unlink-apple","change-email","change-phone","link-google","link-apple","password","session","other-sessions","revoke-all","export","delete"];
 private string UserId=>User.FindFirstValue(ClaimTypes.NameIdentifier)??throw new UnauthorizedAccessException();
 public async Task OnGetAsync(CancellationToken ct){Response.Headers.CacheControl="no-store";if(ExternalFlowId is {} flow&&Request.Query.ContainsKey("confirmed")){try{ExternalProofId=await external.CompleteAsync(User,flow,ct);Operation=PendingOperation??"";SessionId=Guid.TryParse(PendingSessionId,out var pendingSession)?pendingSession:Guid.Empty;Notice="Account confirmed. Review the action and continue.";ExternalFlowId=null;PendingSessionId=null;}catch(AccountSecurityException e){ErrorMessage=e.Message;}}var error=Request.Query["error"].ToString();if(error is "apple_link_failed" or "google_failed" or "link_conflict")ErrorMessage="The sign-in method could not be linked. Please try again.";if(Request.Query["linked"].ToString() is "apple" or "google")Notice="Sign-in method connected.";await Load(ct);}
 private async Task Load(CancellationToken ct){Profile=await management.ProfileAsync(UserId,ct);Preferences=await management.PreferencesAsync(UserId,ct);Identities=await identities.IdentitiesAsync(UserId,ct);Sessions=await management.SessionsAsync(User,ct);Access=await billing.ReadAsync(UserId,ct);DisplayName??=Profile.DisplayName;DisplayTimeZoneId??=Preferences.DisplayTimeZoneId;Language=await languages.GetAsync(UserId)??"en";}
 public async Task<IActionResult> OnPostProfileAsync(CancellationToken ct){try{Profile=await management.UpdateProfileAsync(User,DisplayName,ct);Notice="Profile saved.";}catch(AccountSecurityException e){ErrorMessage=e.Message;}await Load(ct);return Page();}
 public async Task<IActionResult> OnPostPreferencesAsync(CancellationToken ct){try{var language=UiText.Normalize(Language);if(language is null)throw new AccountSecurityException("invalid_language","Choose a supported language.",400);await management.UpdatePreferencesAsync(User,DisplayTimeZoneId,ct);if(!await languages.SetAsync(UserId,language))throw new AccountSecurityException("invalid_language","Choose a supported language.",400);UserLanguageService.WriteCookie(HttpContext,language);return Redirect("/settings/account?preferences=saved");}catch(AccountSecurityException e){ErrorMessage=e.Message;await Load(ct);return Page();}}
 public async Task<IActionResult> OnPostPrepareAsync(CancellationToken ct){if(!Prepared)return BadRequest();await Load(ct);return Page();}
 private string ProofOperation=>Operation switch{"unlink-google" or "unlink-apple"=>"identity-unlink","change-email" or "change-phone"=>"contact-change","session" or "other-sessions"=>"sessions","link-google" or "link-apple"=>"identity-link",_=>Operation};
 private AccountSecurityProof Proof()=>new(CurrentPassword,VerificationId,Code,ExternalProofId);
 public async Task<IActionResult> OnPostSecurityCodeAsync(CancellationToken ct){if(!Prepared)return BadRequest();try{var challenge=await security.StartProofAsync(User,Destination.Contains('@')?"email":"phone",Destination,ct);VerificationId=challenge.VerificationId;RetryAfterSeconds=challenge.RetryAfterSeconds;Notice="A verification code was sent. It expires in 10 minutes.";ModelState.Remove(nameof(VerificationId));}catch(Exception e)when(e is AccountSecurityException or VerificationRateLimitException or VerificationDeliveryException){ErrorMessage=e.Message;}ClearSensitive();await Load(ct);return Page();}
 public async Task<IActionResult> OnPostExternalAsync(CancellationToken ct){if(!Prepared)return BadRequest();try{var flow=await external.StartAsync(User,Provider,ProofOperation,ct);if(flow.AuthorizationUrl is null)throw new AccountSecurityException("provider_unavailable","This sign-in provider is unavailable.",503);ExternalFlowId=flow.FlowId;PendingOperation=Operation;PendingSessionId=SessionId==Guid.Empty?null:SessionId.ToString("D");return Redirect(flow.AuthorizationUrl);}catch(Exception e)when(e is AccountSecurityException or VerificationRateLimitException){ErrorMessage=e.Message;}ClearSensitive();await Load(ct);return Page();}
 public async Task<IActionResult> OnPostActionAsync(CancellationToken ct){if(!Prepared)return BadRequest();try{
 switch(Operation){case "unlink-google":case "unlink-apple":await management.UnlinkAsync(User,Operation=="unlink-google"?"google":"apple",Proof(),ct);Notice="Sign-in method disconnected.";break;
 case "change-email":case "change-phone":var challenge=await management.StartContactChangeAsync(User,Operation=="change-email"?"email":"phone",Destination,Proof(),ct);ChallengeId=challenge.ChallengeId;ContactExpiresAt=challenge.ExpiresAt;RetryAfterSeconds=challenge.RetryAfterSeconds;ContactDestination=Destination;Notice="Verify the new contact before it replaces the current one.";ModelState.Remove(nameof(ChallengeId));break;
 case "link-google":if(!providers.GoogleEnabled)throw new AccountSecurityException("provider_unavailable","This sign-in provider is unavailable.",503);var googleUser=await fresh.ProveAsync(User,Proof(),ct,"identity-link");var properties=new AuthenticationProperties{RedirectUri="/auth/google/complete"};properties.Items["solar.link.user"]=googleUser.Id;properties.Items["solar.oauth.once"]=googleTickets.StartCallback();return Challenge(properties,GoogleIdentityEndpoints.Scheme);
 case "link-apple":if(!providers.Apple.WebAvailable)throw new AccountSecurityException("provider_unavailable","This sign-in provider is unavailable.",503);var appleUser=await fresh.ProveAsync(User,Proof(),ct,"identity-link");var flow=apple.StartLink(appleUser.Id,ExternalAccountProofStore.Hash(User.FindFirstValue(InstallationAccessAuthorizer.SessionClaim)!),appleUser.SecurityStamp??"");return Redirect("/auth/apple?linkFlow="+Uri.EscapeDataString(flow.Id));
 case "password":await security.ChangePasswordAsync(User,new(Proof(),NewPassword),ct);return await SignOut();
 case "session":var sessionIsCurrent=(await management.SessionsAsync(User,ct)).Sessions.Any(s=>s.Id==SessionId&&s.IsCurrent);await management.RevokeSessionAsync(User,SessionId,Proof(),ct);if(sessionIsCurrent)return await SignOut();Notice="Session ended.";break;
 case "other-sessions":await management.RevokeOtherSessionsAsync(User,Proof(),ct);Notice="Other sessions ended. This session stays active.";break;
 case "revoke-all":await security.RevokeAllAsync(User,Proof(),ct);return await SignOut();
 case "export":var zip=await management.ExportZipAsync(User,Proof(),ct);ExternalProofId=null;return File(zip,"application/zip","smartsolar-account.zip");
 case "delete":if(!ConfirmDelete)throw new AccountSecurityException("confirmation_required","Confirm account deletion before continuing.",400);await security.DeleteAsync(User,Proof(),ct);return await SignOut();
 }
 ExternalProofId=null;if(ChallengeId.Length==0)Operation="";
 }catch(Exception e)when(e is AccountSecurityException or AccountIdentityException or VerificationRateLimitException or VerificationDeliveryException or ArgumentException){ErrorMessage=e.Message;}ClearSensitive();await Load(ct);return Page();}
 public async Task<IActionResult> OnPostContactCompleteAsync(CancellationToken ct){try{await management.CompleteContactChangeAsync(User,ChallengeId,ContactCode,ct);ChallengeId="";Operation="";Notice="The verified contact was saved.";ModelState.Remove(nameof(ChallengeId));}catch(AccountSecurityException e){ErrorMessage=e.Message;}ContactCode="";ModelState.Remove(nameof(ContactCode));await Load(ct);return Page();}
 private void ClearSensitive(){CurrentPassword="";NewPassword="";Code="";ModelState.Remove(nameof(CurrentPassword));ModelState.Remove(nameof(NewPassword));ModelState.Remove(nameof(Code));}
 private async Task<IActionResult> SignOut(){await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);return Redirect("/signin");}
 public string? DisplayTime(DateTimeOffset? timestamp){if(timestamp is not {} at)return null;TimeZoneInfo zone;try{zone=TimeZoneInfo.FindSystemTimeZoneById(Preferences.DisplayTimeZoneId??"UTC");}catch(TimeZoneNotFoundException){zone=TimeZoneInfo.Utc;}return TimeZoneInfo.ConvertTime(at,zone).ToString("d MMM yyyy HH:mm zzz");}
 public string ActionTitle=>Operation switch{"unlink-google"=>"Disconnect Google?","unlink-apple"=>"Disconnect Apple?","change-email"=>"Change email","change-phone"=>"Change phone","link-google"=>"Link Google","link-apple"=>"Link Apple","password"=>"Set a password","session"=>"End this session?","other-sessions"=>"End other sessions?","revoke-all"=>"Sign out everywhere?","export"=>"Export your account","delete"=>"Delete your account?",_=>"Confirm account action"};
}
